version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: digicamp-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - digicamp-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourPassword123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: digicamp-backend
    environment:
      - DB_URL=jdbc:sqlserver://sqlserver:1433;databaseName=digicampdb;encrypt=true;trustServerCertificate=true
      - DB_USERNAME=sa
      - DB_PASSWORD=YourPassword123!
      - JWT_SECRET=VotreCleSuperSecreteQuiDoitEtreTresLonguePourPlusDeSecurite123456789
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - digicamp-network
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: digicamp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - digicamp-network
    restart: unless-stopped

volumes:
  sqlserver-data:

networks:
  digicamp-network:
    driver: bridge
