spring:
  application:
    name: digicamp-monitoring
  
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=digicampdb;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourPassword123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:VotreCleSuperSecreteQuiDoitEtreTresLonguePourPlusDeSecurite123456789}
  expiration: 86400000 # 24 hours in milliseconds

# Application Configuration
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost}
  upload:
    directory: ${UPLOAD_DIR:./uploads}

# Logging
logging:
  level:
    com.digicamp.monitoring: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
